CREATE TABLE USUARIOS(
    CODIGO int PRIMARY KEY,
    NOME_COMPLETO VARCHAR(100),
    LOGIN VARCHAR(70),
    SENHA VARCHAR(70),
    NIVEL INT
);

CREATE GENERATOR USUARIOS_GENERATOR;

CREATE or ALTER TRIGGER USUARIO_GENID FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    NEW.CODIGO = GEN_ID(usuarios_generator, 1);
END;

INSERT INTO USUARIOS(NOME_COMPLETO, LOGIN, SENHA, NIVEL)
VALUES('HESLI HENDRIK AZEVEDO', 'HESLI', '1234', 999)

